greenery:

  outputs:
    dbt_zkan:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_zkan

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    dbt_monk_bigquery:
      type: bigquery
      method: service-account
      project: my-project-de-434208
      dataset: dbt_monk
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/skooldio-deb4-bigquery-dbt.json
      location: asia-southeast1

    prod_bigquery:
      type: bigquery
      method: service-account
      project: my-project-de-434208
      dataset: deb_bootcamp
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/skooldio-deb4-bigquery-dbt.json
      location: asia-southeast1

  target: dbt_monk_bigquery